services:
  auth:
    mode: docker
    env:
      PUBLIC_URL: https://local.j26.se/auth
      ALLOWED_REDIRECT_DOMAINS: local.j26.se
      OIDC_SERVER: https://dev.id.scouterna.se/realms/jamboree26
      OIDC_CLIENT_ID: j26-auth-local
      OIDC_CLIENT_SECRET: nFpewcBpLbdwSdcg42zpEDu6omS31u03
  app:
    mode: local
    hostPort: 5173
