# overrides:
#   '@scouterna/ui-react': link:../../../../.local/share/pnpm/global/5/node_modules/@scouterna/ui-react
#   '@scouterna/ui-webc': link:../../../../.local/share/pnpm/global/5/node_modules/@scouterna/ui-webc
