/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteImport } from './routes/_app'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as OnboardingSigninRouteImport } from './routes/onboarding/signin'
import { Route as OnboardingNotificationsRouteImport } from './routes/onboarding/notifications'
import { Route as OnboardingLocationRouteImport } from './routes/onboarding/location'
import { Route as OnboardingLanguageRouteImport } from './routes/onboarding/language'
import { Route as OnboardingFinishedRouteImport } from './routes/onboarding/finished'
import { Route as AppMoreRouteImport } from './routes/_app/more'
import { Route as AppAboutRouteImport } from './routes/_app/about'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppMoreIndexRouteImport } from './routes/_app/more.index'
import { Route as AppHomeIndexRouteImport } from './routes/_app/home/index'
import { Route as AppSettingsNotificationsRouteImport } from './routes/_app/settings/notifications'
import { Route as AppSettingsLanguageRouteImport } from './routes/_app/settings/language'
import { Route as AppInfoIdRouteImport } from './routes/_app/info.$id'
import { Route as AppAppSplatRouteImport } from './routes/_app/app.$'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const OnboardingSigninRoute = OnboardingSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingNotificationsRoute = OnboardingNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingLocationRoute = OnboardingLocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingLanguageRoute = OnboardingLanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingFinishedRoute = OnboardingFinishedRouteImport.update({
  id: '/finished',
  path: '/finished',
  getParentRoute: () => OnboardingRoute,
} as any)
const AppMoreRoute = AppMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppMoreIndexRoute = AppMoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMoreRoute,
} as any)
const AppHomeIndexRoute = AppHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsNotificationsRoute =
  AppSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AppRoute,
  } as any)
const AppSettingsLanguageRoute = AppSettingsLanguageRouteImport.update({
  id: '/settings/language',
  path: '/settings/language',
  getParentRoute: () => AppRoute,
} as any)
const AppInfoIdRoute = AppInfoIdRouteImport.update({
  id: '/info/$id',
  path: '/info/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAppSplatRoute = AppAppSplatRouteImport.update({
  id: '/app/$',
  path: '/app/$',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/about': typeof AppAboutRoute
  '/more': typeof AppMoreRouteWithChildren
  '/onboarding/finished': typeof OnboardingFinishedRoute
  '/onboarding/language': typeof OnboardingLanguageRoute
  '/onboarding/location': typeof OnboardingLocationRoute
  '/onboarding/notifications': typeof OnboardingNotificationsRoute
  '/onboarding/signin': typeof OnboardingSigninRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/app/$': typeof AppAppSplatRoute
  '/info/$id': typeof AppInfoIdRoute
  '/settings/language': typeof AppSettingsLanguageRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/home/': typeof AppHomeIndexRoute
  '/more/': typeof AppMoreIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof AppAboutRoute
  '/onboarding/finished': typeof OnboardingFinishedRoute
  '/onboarding/language': typeof OnboardingLanguageRoute
  '/onboarding/location': typeof OnboardingLocationRoute
  '/onboarding/notifications': typeof OnboardingNotificationsRoute
  '/onboarding/signin': typeof OnboardingSigninRoute
  '/': typeof AppIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/app/$': typeof AppAppSplatRoute
  '/info/$id': typeof AppInfoIdRoute
  '/settings/language': typeof AppSettingsLanguageRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/home': typeof AppHomeIndexRoute
  '/more': typeof AppMoreIndexRoute
  '/settings': typeof AppSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRouteWithChildren
  '/_app/about': typeof AppAboutRoute
  '/_app/more': typeof AppMoreRouteWithChildren
  '/onboarding/finished': typeof OnboardingFinishedRoute
  '/onboarding/language': typeof OnboardingLanguageRoute
  '/onboarding/location': typeof OnboardingLocationRoute
  '/onboarding/notifications': typeof OnboardingNotificationsRoute
  '/onboarding/signin': typeof OnboardingSigninRoute
  '/_app/': typeof AppIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/_app/app/$': typeof AppAppSplatRoute
  '/_app/info/$id': typeof AppInfoIdRoute
  '/_app/settings/language': typeof AppSettingsLanguageRoute
  '/_app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/_app/home/': typeof AppHomeIndexRoute
  '/_app/more/': typeof AppMoreIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/about'
    | '/more'
    | '/onboarding/finished'
    | '/onboarding/language'
    | '/onboarding/location'
    | '/onboarding/notifications'
    | '/onboarding/signin'
    | '/onboarding/'
    | '/app/$'
    | '/info/$id'
    | '/settings/language'
    | '/settings/notifications'
    | '/home/'
    | '/more/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/onboarding/finished'
    | '/onboarding/language'
    | '/onboarding/location'
    | '/onboarding/notifications'
    | '/onboarding/signin'
    | '/'
    | '/onboarding'
    | '/app/$'
    | '/info/$id'
    | '/settings/language'
    | '/settings/notifications'
    | '/home'
    | '/more'
    | '/settings'
  id:
    | '__root__'
    | '/_app'
    | '/onboarding'
    | '/_app/about'
    | '/_app/more'
    | '/onboarding/finished'
    | '/onboarding/language'
    | '/onboarding/location'
    | '/onboarding/notifications'
    | '/onboarding/signin'
    | '/_app/'
    | '/onboarding/'
    | '/_app/app/$'
    | '/_app/info/$id'
    | '/_app/settings/language'
    | '/_app/settings/notifications'
    | '/_app/home/'
    | '/_app/more/'
    | '/_app/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/onboarding/signin': {
      id: '/onboarding/signin'
      path: '/signin'
      fullPath: '/onboarding/signin'
      preLoaderRoute: typeof OnboardingSigninRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/notifications': {
      id: '/onboarding/notifications'
      path: '/notifications'
      fullPath: '/onboarding/notifications'
      preLoaderRoute: typeof OnboardingNotificationsRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/location': {
      id: '/onboarding/location'
      path: '/location'
      fullPath: '/onboarding/location'
      preLoaderRoute: typeof OnboardingLocationRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/language': {
      id: '/onboarding/language'
      path: '/language'
      fullPath: '/onboarding/language'
      preLoaderRoute: typeof OnboardingLanguageRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/finished': {
      id: '/onboarding/finished'
      path: '/finished'
      fullPath: '/onboarding/finished'
      preLoaderRoute: typeof OnboardingFinishedRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_app/more': {
      id: '/_app/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof AppMoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/more/': {
      id: '/_app/more/'
      path: '/'
      fullPath: '/more/'
      preLoaderRoute: typeof AppMoreIndexRouteImport
      parentRoute: typeof AppMoreRoute
    }
    '/_app/home/': {
      id: '/_app/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof AppHomeIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/notifications': {
      id: '/_app/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AppSettingsNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/language': {
      id: '/_app/settings/language'
      path: '/settings/language'
      fullPath: '/settings/language'
      preLoaderRoute: typeof AppSettingsLanguageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/info/$id': {
      id: '/_app/info/$id'
      path: '/info/$id'
      fullPath: '/info/$id'
      preLoaderRoute: typeof AppInfoIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/$': {
      id: '/_app/app/$'
      path: '/app/$'
      fullPath: '/app/$'
      preLoaderRoute: typeof AppAppSplatRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppMoreRouteChildren {
  AppMoreIndexRoute: typeof AppMoreIndexRoute
}

const AppMoreRouteChildren: AppMoreRouteChildren = {
  AppMoreIndexRoute: AppMoreIndexRoute,
}

const AppMoreRouteWithChildren =
  AppMoreRoute._addFileChildren(AppMoreRouteChildren)

interface AppRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppMoreRoute: typeof AppMoreRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppAppSplatRoute: typeof AppAppSplatRoute
  AppInfoIdRoute: typeof AppInfoIdRoute
  AppSettingsLanguageRoute: typeof AppSettingsLanguageRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
  AppHomeIndexRoute: typeof AppHomeIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppMoreRoute: AppMoreRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppAppSplatRoute: AppAppSplatRoute,
  AppInfoIdRoute: AppInfoIdRoute,
  AppSettingsLanguageRoute: AppSettingsLanguageRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
  AppHomeIndexRoute: AppHomeIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface OnboardingRouteChildren {
  OnboardingFinishedRoute: typeof OnboardingFinishedRoute
  OnboardingLanguageRoute: typeof OnboardingLanguageRoute
  OnboardingLocationRoute: typeof OnboardingLocationRoute
  OnboardingNotificationsRoute: typeof OnboardingNotificationsRoute
  OnboardingSigninRoute: typeof OnboardingSigninRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingFinishedRoute: OnboardingFinishedRoute,
  OnboardingLanguageRoute: OnboardingLanguageRoute,
  OnboardingLocationRoute: OnboardingLocationRoute,
  OnboardingNotificationsRoute: OnboardingNotificationsRoute,
  OnboardingSigninRoute: OnboardingSigninRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
