/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MoreRouteImport } from './routes/more'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MoreIndexRouteImport } from './routes/more.index'
import { Route as ScheduleSplatRouteImport } from './routes/schedule.$'
import { Route as MoreLanguageRouteImport } from './routes/more.language'

const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreIndexRoute = MoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MoreRoute,
} as any)
const ScheduleSplatRoute = ScheduleSplatRouteImport.update({
  id: '/schedule/$',
  path: '/schedule/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreLanguageRoute = MoreLanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => MoreRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/more': typeof MoreRouteWithChildren
  '/more/language': typeof MoreLanguageRoute
  '/schedule/$': typeof ScheduleSplatRoute
  '/more/': typeof MoreIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/more/language': typeof MoreLanguageRoute
  '/schedule/$': typeof ScheduleSplatRoute
  '/more': typeof MoreIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/more': typeof MoreRouteWithChildren
  '/more/language': typeof MoreLanguageRoute
  '/schedule/$': typeof ScheduleSplatRoute
  '/more/': typeof MoreIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/more'
    | '/more/language'
    | '/schedule/$'
    | '/more/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/more/language' | '/schedule/$' | '/more'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/more'
    | '/more/language'
    | '/schedule/$'
    | '/more/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  MoreRoute: typeof MoreRouteWithChildren
  ScheduleSplatRoute: typeof ScheduleSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more/': {
      id: '/more/'
      path: '/'
      fullPath: '/more/'
      preLoaderRoute: typeof MoreIndexRouteImport
      parentRoute: typeof MoreRoute
    }
    '/schedule/$': {
      id: '/schedule/$'
      path: '/schedule/$'
      fullPath: '/schedule/$'
      preLoaderRoute: typeof ScheduleSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more/language': {
      id: '/more/language'
      path: '/language'
      fullPath: '/more/language'
      preLoaderRoute: typeof MoreLanguageRouteImport
      parentRoute: typeof MoreRoute
    }
  }
}

interface MoreRouteChildren {
  MoreLanguageRoute: typeof MoreLanguageRoute
  MoreIndexRoute: typeof MoreIndexRoute
}

const MoreRouteChildren: MoreRouteChildren = {
  MoreLanguageRoute: MoreLanguageRoute,
  MoreIndexRoute: MoreIndexRoute,
}

const MoreRouteWithChildren = MoreRoute._addFileChildren(MoreRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  MoreRoute: MoreRouteWithChildren,
  ScheduleSplatRoute: ScheduleSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
